---
-
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    update_cache: true
  name: "Install prerequisites for Docker repository"
-
  apt_key: "url=https://download.docker.com/linux/ubuntu/gpg"
  name: "Add Docker GPG key"
-
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  name: "Add Docker APT repository"
-
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true
  name: "Install Docker CE"
-
  apt:
    name:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev
      - python3-dev
      - python3-setuptools
      - python3-wheel
      - python3-pip
      - virtualenv
  name: "Install prerequisites for docker-compose"
-
  name: "Install docker-compose"
  pip:

    name:
      - cryptography
      - docker-compose
    executable: pip3