--- 
- 
  file: 
    path: /tmp/test1
    state: directory
  name: "create an empty directory if it doesn't exist"
- 
  copy: 
    content: |-
        hello World!!
        Hello World line 2!!
        "the qouts sign fot testing"
    dest: /tmp/test1/helloWorld.txt
    mode: "u=rwx,g=rx,o=rx"
  name: "Create the hello world text file"
